### ISSUE TITLE
Launch Steps

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#103]
- Rename `showcase` to `showcase-old`
- Rename `showcase-test` to `showcase`
- Updates template links/urls
  - 2 links on homepage
  - submit redirect url
- Update `screenshot` post meta url for all posts to point to new URL path (provided the URL changes)
  - They currently have `showcase-test` in their path.   

## Questions
- When we rename the site, will all the media paths change as well?
- How will JetPack cope with that change?
- What other settings will need updating?

**Comment by dd32** [comment]
> Rename showcase-test to showcase

Should be able to perform that on the site info tab: https://wordpress.org/wp-admin/network/site-info.php?id=718 but you may also need to update the `Siteurl` and `Home` items on the Settings tab there too.

> When we rename the site, will all the media paths change as well?

Yes, the path on disk remains the same, but would be available via `https://wordpress.org/showcase/files/` instead.  
I'm not sure if WordPress/the theme will handle that.  WordPress historically would generate the URL on every page render...

If it's using `wp:image` blocks which it appears to be, then the `wp-image-8296` class should be enough to make it update the URLs.. I think.

> How will JetPack cope with that change?

AFAIK it should handle it, but it may require it to re-index.. It's a small site so that shouldn't be too much of an issue hopefully if it comes to that.

> Anything else?

Looking at the DB, there's a few navigational items that appear to have /showcase-test/ in them. 

I would also purge any testing content or submissions if possible.

For changing the URLs, wp-cli's search-replace might be viable: https://developer.wordpress.org/cli/commands/search-replace/

```
 wp search-replace --url=https://wordpress.org/showcase-test '/showcase-test/' '/showcase/' --all-tables-with-prefix --precise --verbose --dry-run
```
That'll also show you the items in the DB that are currently using `showcase-test`.

If that's run as part of the migration, without `dry-run`, you'd also have to run `wp --url=https://wordpress.org/showcase/ cache flush` to flush the cache.

As part of the test, you could also try migrating it to `/showcase-test2/` first
