### ISSUE TITLE
Taxonomy terms page

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#133]
[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

We have several ways of wayfinding:

1. Categories _(we should have only five — ones present in mockups)_
2. Flavors _(we should have only five — ones present in mockups)_
3. Tags

Note. There's back to top button on mobile, which should follow the bottom of the screen, while scrolling.

- [ ] Some copy checking/additions should happen by Stargate.

<table role="table">
<thead>
<tr>
<th>Mobile</th>
<th>Desktop</th>
<th>Monitor</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256120121-312d7d29-abf8-4de3-bf06-afff972010c3.png"><img src="https://user-images.githubusercontent.com/111751264/256120121-312d7d29-abf8-4de3-bf06-afff972010c3.png" alt="(Mobile) Showcase - Tags" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256120092-b5e46376-04f4-4c68-bf76-53447043949a.png"><img src="https://user-images.githubusercontent.com/111751264/256120092-b5e46376-04f4-4c68-bf76-53447043949a.png" alt="(Desktop) Showcase - Tags-1" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256120132-f60ba40b-2327-42f0-b621-e71b0af937d8.png"><img src="https://user-images.githubusercontent.com/111751264/256120132-f60ba40b-2327-42f0-b621-e71b0af937d8.png" alt="(Monitor) Showcase - Tags" style="max-width: 100%;"></a></td>
</tr>
</tbody>
</table>

**Comment by ryelle** [comment]
I've got a first pass of this up at https://wordpress.org/showcase-v2/browse/

This uses two new blocks, "Term Grid" and "Tags Archive". If the "Term Grid" pattern is used again (IIRC it is used in the Learn/Docs/etc mockups), we can move that to wporg-mu-plugins, but for faster development I added it here.

There are currently fewer tags on the site than there are in the mockup, so I was a little worried the alphabetical separation would be sparse, but it's not too bad.

@WordPress/meta-design No PR to review, I deployed the code to the staging site already— feel free to leave any feedback for [this page](https://wordpress.org/showcase-v2/browse/) on this issue, otherwise if it looks good we can close this 🙂

**Comment by jasmussen** [comment]
Nice, at a glance this looks quite good, well done.

The one thing that comes to mind is actually for the tag results page, which looks like this:

<img width="1842" alt="Screenshot 2023-09-20 at 09 08 28" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/e11b3426-e809-4ba7-9d47-24ed9664fea6">

Note here the spacing below the site and above the dots, it's a bit on the short side. I realize this is fully as expected with the mockups, where it's only when pagination is available that it's pushed down the extra 80px, like so:

<img width="1572" alt="Screenshot 2023-09-20 at 09 08 10" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/85383da3-2e95-4af0-9b1d-65b525360958">

But can we do it so that regardless of pagination or not, there's always 80px of space between dots and the last site? I.e. 

<img width="1622" alt="Screenshot 2023-09-20 at 09 08 21" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/aaa73d86-a66c-448c-848d-b45ea1aa70c4">

The way I did it in Figma was to set a fixed height on the pagination box, and just hide the pagination. So visually they could be identical, pagination or not. Let me know if that could work. It's not a blocker or urgent, but would be a nice enhancement.

**Comment by ryelle** [comment]
@jasmussen That's an issue with the archive template, not this page, could you create a new issue for that?

**Comment by ryelle** [comment]
Since there's no feedback on the page itself, I'll consider this page done 👍🏻
