### ISSUE TITLE
Reduce Gap on Mobile between Desktop and Mobile preview images.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#153]
The gap is currently set to `80px` which adds too much of a gap between the images.

| Before (gap: 80px) | After (gap: 20px) |
|--------|--------|
| ![wordpress org_showcase-v2_qualtrics_](https://github.com/WordPress/wporg-showcase-2022/assets/1657336/c80c6953-783c-426e-9b39-8ffadf4c5afa) | ![wordpress org_showcase-v2_qualtrics_ (1)](https://github.com/WordPress/wporg-showcase-2022/assets/1657336/3c5930e0-c6c9-430e-95fb-b3c97bc71c65) |

**Comment by ryelle** [comment]
Hm… I must have lost this change in a rebase, because I remember doing that 😅 

In https://github.com/WordPress/wporg-showcase-2022/commit/eafe8ecab8cc5cfa59ee896f237c2031d0ba6f23 I've updated the gap to use the 20-80px scaling value, so it looks like this:

![Screen Shot 2023-09-18 at 13 37 55](https://github.com/WordPress/wporg-showcase-2022/assets/541093/6a4b10ce-33ce-4c52-ae51-9bb67a3c4d22)

The design does have the two images overlap on small screens, but in the figma, the borders were changed to be opaque — they're supposed to be semi-transparent black, which does not work with the overlap. You can see the content below through the border. @WordPress/meta-design See the example below. Are you okay with leaving them not-overlapped (previous screenshot)?

![Screen Shot 2023-09-18 at 13 39 04](https://github.com/WordPress/wporg-showcase-2022/assets/541093/16464e30-3cbf-40c0-a20a-8f1fcc0b1088)

**Comment by jasmussen** [comment]
I created this codepen as an example of how that overlap could happen while avoiding the opacity problem: https://codepen.io/joen/pen/LYXMBZR?editors=1100

Essentially a stacked box shadow where the bottom box shadow is a fully opaque background color, and the top box shadow being a transparent black. Let me know if that works.

**Comment by ryelle** [comment]
The issue was more about passing down the background color, but I was able to do that after all. This is live on the staging site now, but here are a few screenshots:

| Default color | Custom color | Custom color |
|---|---|---|
| ![](https://github.com/WordPress/wporg-showcase-2022/assets/541093/318c9c76-2414-40e9-84e0-05be4198df1b) | ![](https://github.com/WordPress/wporg-showcase-2022/assets/541093/39474e9c-abe1-42b7-ab5d-24086cfde8eb) | ![](https://github.com/WordPress/wporg-showcase-2022/assets/541093/4860ac8c-8e78-4497-91cc-9595c410aab5) |
