### ISSUE TITLE
Improve mShots mobile loading window.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#154]
When mShots is creating a new snap shot it returns a "Generating Preview" image with dimensions that don't match the final output of the preview window so the mobile phone snaps upwards when an image loads. Can we maybe replace that image with a css loading implementation? 

That will give us:
1. A nicer loading state
2. Remove the upwards jump.

## Image
<img width="1623" alt="Screenshot 2023-09-18 at 6 55 44 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/1657336/b2f3f7f4-0b40-4b0d-98f9-37b595586a76">

**Comment by ryelle** [comment]
As far as the site understands, there's no difference between the two images — this isn't using the react loader from wporg-mu-plugins (and we can't easily switch to it, since it assumes mshots for all URLs, while this uses mshots as a fallback).

I've updated the screenshot to use the correct aspect ratio, so it won't jump anymore, but that doesn't really look any _better_.

![Screen Shot 2023-09-18 at 19 14 44](https://github.com/WordPress/wporg-showcase-2022/assets/541093/901f84b4-a738-4bd7-b717-f9e34bae2a2f)

It would be best if we could combine the code from `wporg/screenshot-preview` with this block, so that the output remains the same (since it's styled correctly this way).
