### ISSUE TITLE
If possible, consider adding white-space: nowrap; to tags in the meta box on the right.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-showcase-2022#169]
If you go to a site such as https://wordpress.org/showcase-v2/arredodalpozzo/, you'll see that the "Interior design" tag wraps onto two lines:

<img width="464" alt="Screenshot 2023-09-20 at 18 48 57" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/1a85c722-2d47-4367-b944-9fb9b9589029">

Question: is it possible and feasible to apply `white-space: nowrap;` to each individual tag so that they don't wrap like this, and ideally get a full line of their own? Like so:

<img width="437" alt="Screenshot 2023-09-21 at 09 51 19" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/3b319676-afbe-4a8f-96c7-7a10342f14fe">

I'm asking because we also want to avoid any cases where doing this means very long tag-names that simply have to wrap suddenly need eliding or otherwise. If that's the case, let's not do it.

Not urgent.

**Comment by ryelle** [comment]
A quick test with what I think is the longest tag, and it does end up breaking out of the container when the screen size changes.

<img width="323" alt="Screenshot 2023-09-21 at 11 42 34 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/6c7eb6f8-7e02-4b7e-aae5-3bc375255331">

My next attempt was the "widont" approach (a `nbsp` in the title), and that just causes it to break in weird places.

<img width="279" alt="Screenshot 2023-09-21 at 11 44 01 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/f5bbb335-8bf2-4bcf-a690-49eccaa572e5"> <img width="243" alt="Screenshot 2023-09-21 at 11 45 27 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/bba287ee-8d3e-49fc-b7fc-cadcb503111b">

So I don't think we'll be able to do this, especially since it only affects ~10 sites (sites with tags with multiple words). I'll hold off on closing for a few days in case anyone else has ideas though.

**Comment by jasmussen** [comment]
Thanks for taking a look!
