### ISSUE TITLE
Content issues group

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#186]
There are a few content issues to be finalized:

⚽️ FOR NESO:
- [x] #187
Note. Once added, I'll make selection of which ones should be there, and send to Marketing for copy help.

- [x] Unpublish the following sites. Leave as drafts, but hide from the Showcase search. 
https://wordpress.org/showcase-v2/dita/
https://wordpress.org/showcase-v2/vogue/
https://wordpress.org/showcase-v2/the-national-puerto-rican-day-parade/
https://wordpress.org/showcase-v2/the-walt-disney-company/
https://wordpress.org/showcase-v2/toyota-motors-brasil/
https://wordpress.org/showcase-v2/method-products/
https://wordpress.org/showcase-v2/quartz/

🏀 / FOR MARKETING:
- [ ] Only 85 sites will give a shallow sense of depth of WP. Which is something the team is looking at and could perhaps happen in phases.
Note. **A thing to be left for further discussion. Nothing to do at the moment.**

- [ ] https://wordpress.org/showcase-v2/museo-nacional-thyssen-bornemisza/ website needs different link preview (true link is already in metadata, just the preview one needs editing). Copy edit.

**Comment by ryelle** [comment]
@marko-srb I've changed the posts to drafts, but for future reference you should have access to do that yourself. I also changed the first item to its own issue, in general that's easier to handle for dev work (1 issue per task).

**Comment by marko-srb** [comment]
@ryelle Is it ok to have the 'meta issue' and then separate issues from there? Or its better to have only separate issues themselves?

It seems to me that unless we categorize, we won't be able to keep track of anything really. And its been the case on the last 3 sites I worked on, hence the question. Thank youuu!

**Comment by ryelle** [comment]
> It seems to me that unless we categorize, we won't be able to keep track of anything really.

We have the labels (ex, [Needs design/design feedback](https://github.com/WordPress/wporg-showcase-2022/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BStatus%5D+Needs+Design%22%2C%22%5BStatus%5D+Needs+Design+Feedback%22)), assignments/review-requests, & [project board](https://github.com/orgs/WordPress/projects/40/views/13) for help with keeping track of things.

I dislike "meta issues" personally, because in my experience, they don't have scope to them, and they're very hard to close. I've mostly been breaking your big issues into separate ones for my own work, then circling back and closing the meta issue once I've created the task-issues.

Other Neso devs might have different preferences, but usually 1 issue per task is good because then we can close the issue with a single commit/PR.

**Comment by marko-srb** [comment]
One issue per task it is. Can you help me to learn how to find an existing issue (this one we are chatting about for example) in that project board list? Thanks!

**Comment by ryelle** [comment]
I haven't added this issue to the project board because it's not a single-task issue. Your first request, to update the featured grid on the homepage, is a new issue and it's 3rd in the "To do" column. I add issues to the board manually, if they're part of the work required for launch. I've been less strict about this with the issues that are just content/design, though.

You can check the status of an issue in the "Projects" area on the issue itself:
<img width="524" alt="Screenshot 2023-09-27 at 4 40 49 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/60c74bb3-dd0e-460e-87ed-62e5dd2c36ed">
