### ISSUE TITLE
Fix Jetpack dropdown styling

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#207]
A dropdown has been added to the [Submit](https://wordpress.org/showcase-v2/submit-a-wordpress-site/) form, but it's lacking styling: 

<img width="500" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/33e8064c-6935-4d4d-8ba6-570a2790ed0d">

In playing around with it, I believe the styling for the main field should be: 

```
.wp-block-jetpack-contact-form .contact-form-dropdown, 
.wp-block-jetpack-contact-form .contact-form-dropdown__button {
	max-width: 400px;
	border: 1px solid var(--wp--preset--color--charcoal-5)!important;
	border-radius: var(--wp--custom--form--border--radius)!important;
	padding-block: var(--wp--custom--form--padding--block)!important;
	padding-inline: var(--wp--custom--form--padding--inline)!important;
}
```

But not sure how the dropdown should be styled. Any ideas @marko-srb @jasmussen?

This is what it looks like with the above CSS applied: 

<img width="500" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/4e0523d2-156c-41da-94bd-ea310c4a702f">

**Comment by marko-srb** [comment]
We had the style of the cheveron in the design. 

Overall, shouldn't it be the same as on the filters? 
Just a gray instead of blueberry. That black is fine from the screenshot, but maybe Charcoal #40464D. Cheveron should be smaller ideally, but not urgent...

Here's a preview:
<img width="978" alt="Screen Shot 2023-09-28 at 19 31 44" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/5780c7d7-c818-4c0a-9ff0-16cef330a243">

@jasmussen if you have any thoughts here, feel free to jump in, but I believe styling should be same/similar as much as possible.

**Comment by ndiego** [comment]
That looks good. Here is the [Figma link](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=4463-25261&mode=design&t=WtNRyDVBWFEEPkc5-0).

**Comment by jasmussen** [comment]
Agreed, that looks good.

**Comment by ndiego** [comment]
@ryelle I am not seeing this update on the live site 🤔

**Comment by ryelle** [comment]
That's correct — I didn't want to deploy and then leave for the weekend.

**Comment by ndiego** [comment]
Looks better than it did

<img width="400" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/fffd4fe4-f7c7-46ff-968a-5732ffa1adeb">
