### ISSUE TITLE
Site link block: Add URL path to link display

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#211]
I am not sure how to do this. I did place the right link in metadata, but am not sure how to replace the preview link on this post:

https://wordpress.org/showcase-v2/museo-nacional-thyssen-bornemisza/

So, the link that should be visible is: www.museothyssen.org/webdocs/conectathyssen/artistas-migrantes instead of the short one.

I can do this, if someone can point me to how. :)

**Comment by ryelle** [comment]
That's not how this is intended to work— in order for this to be a "pretty url" for display, the URL entered is stripped down to just the "domain.com" part. Otherwise they'd all be displaying "https://www.gv.com/", "https://ageofunion.com/".

The code could probably be updated to show the path too, so it could show "museothyssen.org/webdocs/conectathyssen/artistas-migrantes"

**Comment by marko-srb** [comment]
Oh, that makes sense. That preview line works well Kelly. Thank you!
