### ISSUE TITLE
Sorting option: We should add 'oldest'

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#215]
We should add 'oldest' option in the sorting, and maybe remove by 'title' option — it doesn't seem useful, unless it was specifically asked for...

![Screen Shot 2023-09-28 at 21 29 22](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/96053abe-b981-409c-bedc-7cfdac906593)

CC: @jasmussen , @eidolonnight

**Comment by jasmussen** [comment]
Yep, I don't know that this needs to be blocked on discussion, honestly. Title reads like a mistake to me in the context.

**Comment by marko-srb** [comment]
@eidolonnight 

Do we need by 'title'? Or we can have only 'newest' and 'oldest'?

**Comment by ryelle** [comment]
"Title" _is_ basically a placeholder, I added it because the mockups only had "Newest" and "Popular", though "Featured" also came up— we have no meta for "popular", and "featured" is a binary, not a sort. So it would have been a dropdown with one item. Happy to update it to "Alphabetical" or remove it.

I think we can add Oldest- it's not quite as simple as dropping in a new field, but it should be fine.

**Comment by eidolonnight** [comment]
> Do we need by 'title'? Or we can have only 'newest' and 'oldest'?

This is closed, but I didn't want to leave this question hanging. Based on past usage, all these sorting and filtering mechanisms are seldom used, so we can put whatever in there.
