### ISSUE TITLE
Header & Content/Footer alignment doesn't match.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#62]
Footer & Content padding works the same. It uses `clamp` to provide responsive padding around the outer container. The header does not. The result is that the content does not match the header/subnav alignment.

## Example
<img width="500px" src="https://user-images.githubusercontent.com/1657336/204203424-2babb839-114f-42c1-9cda-5273badbc7c2.gif" />

I'm not certain which way we should go since the header recently went through some changes in https://github.com/WordPress/wporg-mu-plugins/pull/302.

@ryelle Thoughts?

**Comment by StevenDufresne** [comment]
@ryelle I see you make some changes in [2ca5e5b](https://github.com/WordPress/wporg-mu-plugins/commit/2ca5e5ba0046f5fa384a504ffe07df0b2b29a6c4).

What else is needed for this?

**Comment by ryelle** [comment]
> What else is needed for this?

I'm not totally sure what else Showcase would need. In Documentation, I added [a local override](https://github.com/WordPress/wporg-documentation-2022/blob/trunk/source/wp-content/themes/wporg-documentation-2022/src/style/style.scss#L6) of the `--wp--preset--spacing--60` variable, and then I'm using that (Large padding) on the left/right of my full-width containers — seems to be working out for that site. Maybe you can do something similar?

I added a note about moving that override back to the parent theme - if this works for you in Showcase too, we definitely should just update the value in `wporg-parent-2021`.

**Comment by StevenDufresne** [comment]
I think the problem is that the content quickly _misaligns_ with the subnav as the viewport grows because it's responsive while the header and subnav are not.

<img width="665" alt="Screen Shot 2022-12-02 at 8 12 03 PM" src="https://user-images.githubusercontent.com/1657336/205280200-9c29f529-3c46-4a18-b56b-a72fcbe1976a.png">

**Comment by StevenDufresne** [comment]
After giving this a try, I think we should just remove responsive clamping on all outer containers to match the header (content & footer) for wp.org. 

Does anyone have any thoughts on this @ryelle @adamwoodnz @renintw ?

**Comment by adamwoodnz** [comment]
> After giving this a try

Would you be able to push a branch with this? I'll find it easier to provide input after testing I think

**Comment by adamwoodnz** [comment]
Just had a quick look. If we do adopt the header padding for the content, it seems the one format which might not have a desirable layout is tablet portrait, where the central space (gap) will be considerably larger than the edge space. The edge space will be quite tight.

| Tablet landscape | Tablet portrait |
|-|-|
| ![wordpress org_showcase-test_archives_(iPad Air) (1)](https://user-images.githubusercontent.com/1017872/206307458-bca036fb-50dc-4d2b-a2ff-26283009aa9d.png) | ![wordpress org_showcase-test_archives_(iPad Air)](https://user-images.githubusercontent.com/1017872/206307287-aa4e07c2-c331-4349-9ad7-9b55f8aac677.png) |

**Comment by ryelle** [comment]
> I think the problem is that the content quickly misaligns with the subnav as the viewport grows because it's responsive while the header and subnav are not.

Header, subnav, and (as of https://github.com/WordPress/wporg-mu-plugins/commit/2ca5e5ba0046f5fa384a504ffe07df0b2b29a6c4) the footer, _are_ all responsive, it's just a cliff 80/20px rather than the scaled clamp.

> We'll need to adopt those properties and remove the clamping by overriding it (--wp--preset--spacing--60). 

Yes, that's what I was trying to suggest in https://github.com/WordPress/wporg-showcase-2022/issues/62#issuecomment-1334530729 by showing [the CSS code from documentation](https://github.com/WordPress/wporg-documentation-2022/blob/d7ed8d1f836364da5dbeddfac5b4e2168ab40700/source/wp-content/themes/wporg-documentation-2022/src/style/style.scss#L6-L21). Then in the templates, whatever top-level full-width container you have should get left  & right padding of `--wp--preset--spacing--60`, for example, [this in `archive.html`](https://github.com/WordPress/wporg-documentation-2022/blob/d7ed8d1f836364da5dbeddfac5b4e2168ab40700/source/wp-content/themes/wporg-documentation-2022/templates/archive.html#L3-L4).

Once things have calmed down a little, we can look at whether `--wp--preset--spacing--60` should be updated in the parent, or whether this should actually be a separate custom property.

**Comment by StevenDufresne** [comment]
Ok. I think we can launch with the layout as is. I'll update the milestone to reflect that.

**Comment by ryelle** [comment]
I've set up [an issue to track fixing this in all the child themes](https://github.com/WordPress/wporg-parent-2021/issues/65), since if we make the change in the parent theme first, it could break alignment in the child themes.

**Comment by ryelle** [comment]
Closing this, if it's still valid it'll be fixed with #130.
